version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    groups:
      dev-dependencies:
        dependency-type: "development"
      minor-changes:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    assignees:
      - slowli

  - package-ecosystem: npm
    directory: "/e2e-tests/wasm"
    schedule:
      interval: daily
      time: "03:00"
    groups:
      minor-changes:
        update-types:
          - "minor"
          - "patch"
    open-pull-requests-limit: 10
    assignees:
      - slowli
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-patch"]
