dist: xenial
addons:
  apt:
    sources:
      - sourceline: 'ppa:fsgmhoward/shadowsocks-libev'
    packages:
      - libsodium-dev

language: rust
rust:
  - 1.39.0
cache:
  - cargo

branches:
  only:
    - master
    # GitHub release tags (for example "v0.9" or "v0.9.1").
    - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
    # Branch names endings with "-release" (for example "0.9.0-release").
    - /-release$/
stages:
  - test
  - name: deploy
    if: branch = master

env:
  global:
    - RUSTFLAGS="-D warnings"
    - DEADLINKS_VERS=0.4.1


jobs:
  include:
    - stage: test
      install:
        - cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
        - rustup component add rustfmt
        - rustfmt -V
        - rustup component add clippy
        - cargo clippy -V
      script:
        - cargo fmt --all -- --check
        - cargo clippy --features secp256k1 --lib --tests -- -D warnings
        - cargo clippy --no-default-features --features ed25519-dalek --lib --tests -- -D warnings
        - cargo test --features secp256k1 --lib --tests
        - cargo test --no-default-features --features ed25519-dalek --lib --tests
        - cargo test --doc
        - cargo clean --doc && cargo doc --features secp256k1 --no-deps && cargo deadlinks --check-http

    - stage: deploy
      rust: nightly-2020-01-05
      script:
        - |
          cargo clean --doc && \
          cargo rustdoc --features secp256k1 -- -Z unstable-options \
            --extern-html-root-url base64=https://docs.rs/base64/~0.12 \
            --extern-html-root-url exonum-crypto=https://docs.rs/exonum-crypto/~0.12 \
            --extern-html-root-url failure=https://docs.rs/failure/~0.1 \
            --extern-html-root-url digest=https://docs.rs/digest/~0.8 \
            --extern-html-root-url hmac=https://docs.rs/hmac/~0.7 \
            --extern-html-root-url crypto-mac=https://docs.rs/crypto-mac/~0.7 \
            --extern-html-root-url secp256k1=https://docs.rs/secp256k1/~0.17 \
            --extern-html-root-url serde_json=https://docs.rs/serde_json/~1 \
            --extern-html-root-url serde_cbor=https://docs.rs/serde_cbor/~0.11
      deploy:
        provider: pages
        local-dir: target/doc
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
