[package]
name = "jwt-compact"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
keywords = ["JWT", "token", "authorization"]
categories = ["web-programming", "cryptography"]
description = "Minimalistic JWT implementation with focus on type safety and secure cryptographic primitives"
repository = "https://github.com/slowli/jwt-compact"

[dependencies]
base64 = "0.10.1"
chrono = "0.4.7"
clear_on_drop = "0.2.3"
failure = "0.1.5"
failure_derive = "0.1.5"
rand_core = "0.4.0"
serde = "1.0"
serde_cbor = "0.9.0"
serde_derive = "1.0"
serde_json = "1.0"
smallvec = "0.6.10"

# Crypto backends
hmac = "0.7.0"
sha2 = "0.8.0"
exonum-crypto = { version = "0.11.0", optional = true }
ed25519-dalek = { version = "1.0.0-pre.1", optional = true }
secp256k1 = { version = "0.13.0", optional = true }

[dev-dependencies]
assert_matches = "1.3.0"
hex-buffer-serde = "0.2.0"
rand = "0.6.5"

[features]
default = ["exonum-crypto"]
