[package]
name = "jwt-compact"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "Apache-2.0"
keywords = ["JWT", "token", "authorization"]
categories = ["web-programming", "cryptography"]
description = "Minimalistic JWT implementation with focus on type safety and secure cryptographic primitives"
repository = "https://github.com/slowli/jwt-compact"

# Enable `ES256K` algorithm in documentation on `docs.rs`.
[package.metadata.docs.rs]
features = ["secp256k1"]

[dependencies]
base64 = "0.12.0"
chrono = "0.4.11"
failure = "0.1.7"
rand_core = "0.5.1"
serde = { version = "1.0", features = ["derive"] }
serde_cbor = "0.11.1"
serde_json = "1.0"
smallvec = "1.2"
zeroize = { version = "1.1", features = ["zeroize_derive"] }

# Crypto backends
hmac = "0.7.1"
sha2 = "0.8.1"
exonum-crypto = { version = "0.12.0", optional = true }
ed25519-dalek = { version = "1.0.0-pre.3", optional = true }
secp256k1 = { version = "0.17.2", optional = true }

[dev-dependencies]
assert_matches = "1.3"
hex = "0.4.2"
hex-buffer-serde = "0.2.0"
rand = "0.7.3"

[features]
default = ["exonum-crypto"]
