[package]
name = "jwt-compact-wasm"
version = "0.0.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Testing usability of `jwt-compact` in WASM"
repository = "https://github.com/slowli/jwt-compact"
publish = false

[package.metadata.wasm-pack.profile.release]
wasm-opt = ["-Os", "--enable-mutable-globals"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = { version = "0.2.68", features = ["serde-serialize"] }

chrono = { version = "0.4.19", features = ["wasmbind"] }
serde = "1.0"

# Multiple other dependencies lead to `serde/std` being enabled
# (e.g., `wasm-bindgen/serde-serialize`, `getrandom/js`).
# Hence, we enable `serde_cbor/std` to avoid compilation errors.
serde_cbor = "0.11.1"

# TODO: enabling `rand_core/getrandom` is not obvious; should RSA support be a crate feature?
rand_core = { version = "0.6", features = ["getrandom"] }
getrandom = { version = "0.2", features = ["js"] }

[dependencies.jwt-compact]
version = "0.4.0"
path = "../.."
default-features = false
features = ["clock", "ed25519-compact", "rsa", "k256"]
