name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Cache cargo bins
        uses: actions/cache@v1
        with:
          path: ~/.cargo/bin
          key: ${{ runner.os }}-cargo-bin
      - name: Cache cargo build
        uses: actions/cache@v1
        with:
          path: target
          key: ${{ runner.os }}-cargo-build-target

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.39.0
          override: true
          components: rustfmt, clippy
      - name: Install deadlinks
        run: cargo deadlinks -V | grep $DEADLINKS_VERS || cargo install cargo-deadlinks --vers $DEADLINKS_VERS --force
        env:
          DEADLINKS_VERS: 0.4.1

      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check
      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --features secp256k1 --all-targets
      - name: Clippy dalek crypto
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --no-default-features --features ed25519-dalek --all-targets

      - name: Run tests
        uses: actions-rs/cargo@v1
        with:
          command: test --features secp256k1
      - name: Test dalek crypto
        uses: actions-rs/cargo@v1
        with:
          command: test --no-default-features --features ed25519-dalek --lib --tests
      - name: Run example
        uses: actions-rs/cargo@v1
        with:
          command: run
          args: --example ed25519_dalek --no-default-features

      - name: Check docs
        run: cargo clean --doc && cargo doc --all-features --no-deps && cargo deadlinks --dir target/doc
